version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mockito_bank  # Automatically creates the database
    ports:
      - "3306:3306"